### ISSUE TITLE
periodic boundary conditions in the new order parameter code

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#12]
Should the jumps over periodic boundaries be removed also for the new order parameter calculation code https://github.com/NMRLipids/MATCH/blob/master/scripts/calcOrderParameters.py
or does it take them into account?

**Comment by hsantila** [comment]
Yes, bonds spanning over boundaries should be removed beforehand. Otherwise an error is raised at line 116.

I'll add a note to the header for now.

**Comment by ohsOllila** [comment]
Thanks. How about removing the water, which was done before, is it still required?

**Comment by hsantila** [comment]
I think that was done to save space and/or speed up the analysis, but it is
not necessary to
get the right results

2018-04-17 17:25 GMT+02:00 ohsOllila <notifications@github.com>:

**Comment by jmelcr** [comment]
PBC has to be checked before the use of the script -- there is only a small check for a common bond-length, which would stop the script from running if the bond length is too large (e.g. C - H split by PBC).

You can remove water molecules to save space, but it is not necessary.

**Comment by jmelcr** [comment]
Jumping of molecules over PBC is not a problem, the molecules only have to be "whole" (or at least the studied moieties).

**Comment by ohsOllila** [comment]
I removed the water removal from the shell script calculating order parameter in commit https://github.com/NMRLipids/MATCH/commit/88228f5a0f858663d2b03a85906f72e8e91b6144. This makes it more simply and it requires less input files.
