### ISSUE TITLE
Wrong slice size in Form Factor script

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/MATCH#50]
There was a bug in determining the slice size in the Form Factor calculation script, see

https://github.com/NMRLipids/MATCH/pull/49/commits/77119e5a00598161811c5d2f11245231dc14dfcc

The bug mainly affects the heights of the lobes, not the zeros. But this might possibly affect some results obtained with this script?

**Comment by ohsOllila** [comment]
There is a new form factor code in the databank: https://github.com/NMRLipids/Databank/blob/main/Scripts/AnalyzeDatabank/calc_FormFactors.py. Therefore this issue is outdated and I will close it.
