### ISSUE TITLE
https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPE/T310K/MODEL_LIPID17_500lipids

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#78]
This dataset is in the POPE folder without ions, but the top file in Zenodo has 500 Na ions and seems to contain POPG

https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPE/T310K/MODEL_LIPID17_500lipids

**Comment by peonqan** [comment]
Thanks, I update the files in Zenodo. Now,  the new one is https://zenodo.org/record/3378970#.XWVSGvx7mHk
