### ISSUE TITLE
https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPG%2B150mNaCl/T310K/MODEL_GROMOS-CKP

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#79]
The data link in this one https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPG%2B150mNaCl/T310K/MODEL_GROMOS-CKP

seems to lead to a system with counterions only, even though the folder is for 150 mM NaCl.

**Comment by peonqan** [comment]
I just saw it.  I changed the file topol.top into zenodo the rest is fine.  Now it is https://zenodo.org/record/3378992 .
