### ISSUE TITLE
Possibly incorret tpr file in this repo: https://doi.org/10.5281/zenodo.3237488

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#82]
It seems to me that this repo may contain incorrect tpr file: https://doi.org/10.5281/zenodo.3237488

**Comment by peonqan** [comment]
I added a new one and also I update the readme file with the new version.

**Comment by ohsOllila** [comment]
This works now and I have added the ion density profile from this simulation into the manuscript: https://github.com/NMRLipids/NMRlipidsIVPEandPG/commit/dc6ff1e6bef28d11d7892c59f07afec991d2f2bd
