### ISSUE TITLE
README.md and other files missing from https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPG%2B30%25POPC/T310K/MODEL_CHARMM36

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/MATCH#83]
https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPG%2B30%25POPC/T310K/MODEL_CHARMM36

**Comment by peonqan** [comment]
I added the file

**Comment by ohsOllila** [comment]
This data is now added to the manuscript: https://github.com/NMRLipids/NMRlipidsIVPEandPG/commit/ece942fea696e0977c67bb581216b44afe529ea0
