### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by SimoneScrima** [NMRLipids/MATCH#85]
Good day to all,
I am currently writing a program for a publication and I would like to include the code for the computation of the order parameter. However, since the License file is not present in the repo I was wondering if it can actually be used or not. Thanks for the availability!

**Comment by ohsOllila** [comment]
Thanks for pointing this out. Idea was that all the NMRlipids repositories would be under the same license as the original repository for the NMRlipids I project, but I noticed that I had not copied the license to all repositories. This should be now fixed. I will close this, please reopen if something is unclear.
