### ISSUE TITLE
Lipid14 tail order parameters

### ISSUE THREAD

**Issue by hsantila** [NMRLipids/MATCH#9]
In lipid14 the (tail) atom names are not unique. When using amber the issue is counteracted by the fact that the tails are defined as different residues. This is, however, not possible(?) when using the lipid14 within gromacs, the lipid consists of a single residues (see, eg. https://doi.org/10.5281/zenodo.12767) ,and the current python script for calculating the (tail) order parameters won't work.

Also note that using the lipid14 OP definition file (https://github.com/NMRLipids/MATCH/blob/master/scripts/orderParm_defs/order_parameter_definitions_slipids_POPC_all.def) suffers from the same issue and will cause an error in the calculation in the lines 179 of calcOrderParameters.py

**Comment by jmelcr** [comment]
You're not the first to hit this =]

I worked around this problem by appending "p" to all atoms in palmitoyl in files: topology (*.gro or something), an OP definition file.

Alternatively, you can split the lipid into 2 (or 3) residues -- Name head group and palmitoyl as "residue POPC", an oleyoyl as "residue OLE" or anything to your liking and modify the OP definition file accordingly.

Alternatively II. =]
Use the [Lipid14 topologies](https://github.com/jmelcr/ecc_lipids/blob/master/topologies/lipid14_popc_top/lipid14-POPC_charmm36-atomic-names.itp), which have the names and order of atoms like in CHARMM36 lipids (can be used directly with charmm-gui - generated membranes).

Enjoy!

**Comment by hsantila** [comment]
Hi,

yes, I know there are ways of working around this:) I raised the issue
because, as you said, I'm probably not the only one to run into it and we
could either improve the OP code or document the workarounds somehow in the
github.

Best,

Hanne

2018-06-25 10:09 GMT+02:00 Josef Melcr <notifications@github.com>:

**Comment by ohsOllila** [comment]
Also, at least, MacRog POPC simulations with 50% (https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPC%2B50%25chol/T310K/MODEL_MACROG) and without (https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPC/T310K/MODEL_MACROG) cholesterol have some overlapping atom names and order parameters for some segments cannot be calculated.

**Comment by ohsOllila** [comment]
In the new databank this is solved with a optional third column in mapping file which defines the residue name. See instructions in here:  https://github.com/NMRLipids/Databank/blob/main/Scripts/BuildDatabank/info_files/README.md
